version: "3.9"
services:
  ftp1:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-docker
    expose:
      - "3000"
    volumes:
      - ./files:/files
      - ./output:/output
  ftp2:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-docker2
    environment:
      PORT: 5000
    expose:
      - "5000"
    volumes:
      - ./files:/files
      - ./output2:/output
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ftp1
      - ftp2
    ports:
      - "4000:80"
